from dydx3.constants import API_HOST_SEPOLIA, API_HOST_MAINNET
from decouple import config

# SELECT MODE
MODE = "DEVELOPMENT" # "PRODUCTION"

# Close all open positions and orders
CLOSE_ALL_POSITIONS = True

# Find cointegrated pairs
FIND_COINTEGRATED_PAIRS = False

# Manage exits
MANAGE_EXITS = True

# Place Trades
PLACE_TRADES = True

# Resolution
RESOLUTION = "1HOUR"

# Stats window
WINDOW = 21

# Thresholds - Opening
MAX_HALF_LIFE = 24
Z_SCORE_THRESHOLD = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880

# Thresholds - Closing
CLOSE_AT_Z_SCORE_CROSS = True

# TESTNET
ETHEREUM_ADDRESS_TESTNET = config("ETHEREUM_ADDRESS_TESTNET")
ETH_PRIVATE_KEY_TESTNET = config("ETH_PRIVATE_KEY_TESTNET")

STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# MAINNET
ETHEREUM_ADDRESS_MAINNET = config("ETHEREUM_ADDRESS_MAINNET")
ETH_PRIVATE_KEY_MAINNET = config("ETH_PRIVATE_KEY_MAINNET") 

STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - Export
ETHEREUM_ADDRESS = ETHEREUM_ADDRESS_TESTNET if MODE == "DEVELOPMENT" else ETHEREUM_ADDRESS_MAINNET
ETH_PRIVATE_KEY = ETH_PRIVATE_KEY_TESTNET if MODE == "DEVELOPMENT" else ETH_PRIVATE_KEY_MAINNET

STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_TESTNET if MODE == "DEVELOPMENT" else STARK_PRIVATE_KEY_MAINNET
DYDX_API_KEY = DYDX_API_KEY_TESTNET if MODE == "DEVELOPMENT" else DYDX_API_KEY_MAINNET
DYDX_API_SECRET = DYDX_API_SECRET_TESTNET if MODE == "DEVELOPMENT" else DYDX_API_SECRET_MAINNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_TESTNET if MODE == "DEVELOPMENT" else DYDX_API_PASSPHRASE_MAINNET

# API HOST - Export
API_HOST = API_HOST_SEPOLIA if MODE == "DEVELOPMENT" else API_HOST_MAINNET

# HTTP PROVIDER
HTTP_PROVIDER = "https://eth-mainnet.g.alchemy.com/v2/tTkLrrep6gje2rmUI8ZYe2dcdgLULboe" if MODE == "PRODUCTION" else "https://eth-sepolia.g.alchemy.com/v2/rrjOCTZkiQgKiUJGV11whXSgv0gacL-3"

# TELEGRAM BOT
TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = config("TELEGRAM_CHAT_ID")

